name: Deploy to Vercel

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy to Vercel on release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Set up environment variables
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "Event name: ${{ github.event_name }}"
            echo "Tag name: ${{ github.event.release.tag_name }}"
            if [[ "${{ github.event.release.tag_name }}" == prod_* ]]; then
              echo "DEPLOY_ENV=production" >> $GITHUB_OUTPUT
            else
              echo "DEPLOY_ENV=preview" >> $GITHUB_OUTPUT
            fi
          fi

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=${{ steps.set-env.outputs.DEPLOY_ENV }} --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.PROJECT_ID }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.PROJECT_ID }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --environment=${{ steps.set-env.outputs.DEPLOY_ENV }} --token=${{ secrets.VERCEL_TOKEN }} --scope=${{ secrets.PROJECT_ID }}
