name: Deploy Website

on:
  push:
    branches:
      - main  # Adjust this to your main branch name or use '*' for all branches

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Next.js project
        run: npx next build
        
      - name: Vercel Action
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: ${{ steps.set-env.outputs.DEPLOY_ENV == 'production' && '--prod' || '' }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: .  # Adjust the directory if needed
