name: Deploy Website

on:
  release:
    types:
      - published
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up environment variables
        id: set-env
        run: |
          if [ "${{ github.event_name }}" == "release" ]; then
            echo "Event name: ${{ github.event_name }}"
            echo "Tag name: ${{ github.event.release.tag_name }}"
            if [[ "${{ github.event.release.tag_name }}" == prod_* ]]; then
              echo "DEPLOY_ENV=production" >> $GITHUB_OUTPUT
            else
              echo "DEPLOY_ENV=preview" >> $GITHUB_OUTPUT
            fi
          fi


        
      - name: Vercel Action
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: ${{ steps.set-env.outputs.DEPLOY_ENV == 'production' && '--prod' || '' }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          working-directory: .  # Adjust the directory if needed
